### ISSUE TITLE
Problem when viewing tiles

### ISSUE THREAD

**Issue by kttary** [ngageoint/geopackage-android-map#13]
I import raster file to geopackage but i can see the tiles on android. However if i use geopackage viewer, the raster tile visible correctly. I have check the zoom level, and the coverage of the image on my emulator, all went well. No error at debugging console. [here is the geopackage](https://www.dropbox.com/s/u20gu7hqrfv51bm/demo-2.gpkg?dl=0)

<img width="1106" alt="screen shot 2018-10-19 at 14 15 22" src="https://user-images.githubusercontent.com/39557649/47203498-c2266f80-d3aa-11e8-9b99-47439c5d80cc.png">

**Comment by kttary** [comment]
Sorry, it was my mistake

**Comment by kttary** [comment]
I'm sorry it a little bit messy. My question is i can open it both from geopackage viewer and android map but qgis. Just want to know if it problem with qgis or i did a mistake when importing the raster?

**Comment by bosborn** [comment]
It appears to work fine in Android.

![screenshot_20181019-075728](https://user-images.githubusercontent.com/11667761/47223161-c2f0de80-d375-11e8-9d6f-32df2330382a.png)

And if I enable tile scaling on the tile layer, you can see the level 15 tiles without zooming as far in.

![screenshot_20181019-075804](https://user-images.githubusercontent.com/11667761/47223195-de5be980-d375-11e8-8464-51e4f84bf742.png)

I did not try it on qgis but didn't see any obvious errors from visible database inspection.
If your problem is that qgis will not display a valid GeoPackage, you could [submit them a bug](https://issues.qgis.org/projects/qgis/issues/).

**Comment by restjohn** [comment]
I was able to get the rasters to display in QGIS 3.2 on my Mac.  First, find the **_Browser_** panel, which for me is located in the upper left corner of the window by default.  If not, click the **_View_** menu > **_Panels_** > **_Browser_** to display it.  I right-clicked the **_GeoPackage_** node in the **_Browser_** panel, then **_New Connection..._**, then browse to and select `demo-2.gpkg`.  I zoomed the QGIS canvas to the area where your tiles are.  I expanded the **_demo-2.gpkg_** node in the **_Browser_** panel and double-clicked the **_PETADASAR_** node to add the layer to the **_Layers_** panel and to the canvas.

All that being said, before I actually knew where your tiles were located, I simply tried to drag-and-drop `demo-2.gpkg` into the QGIS **_Layers_** panel, then right-click the layer node and **_Zoom to Layer_**.  That action just about melted my laptop because QGIS (and GDAL under the hood) seem to have a hard time with your GeoPackage.  Then QGIS finally zoomed out to the bounds of the whole world.  When I modified the `PETADASAR` row in the `gpkg_contents` such that the `min_x`, `min_y`, `max_x`, `max_y` column values matched those in the `gpkg_tile_matrix_set` table, I was able to drag-and-drop the GeoPackage file to the QGIS **_Layers_** panel and **_Zoom to Layer_** without trouble.

So, as @bosborn said, I believe the issue is a combination of QGIS/GDAL and the values I referenced above in your `gpkg_contents` table.

<img width="1151" alt="screen shot 2018-10-19 at 9 42 29 am" src="https://user-images.githubusercontent.com/1292665/47230958-e3766400-d388-11e8-9d0d-db026c5f70b5.png">
